# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 05:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangobin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='tag',
            new_name='tags',
        ),
    ]
