# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobin', '0004_auto_20180507_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='highlighted_code',
            field=models.TextField(blank=True, help_text='Read only field. Will contain the syntax-highlited version of the original code.'),
        ),
    ]
