# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobin', '0005_auto_20180507_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='hits',
            field=models.IntegerField(default=0, help_text='Read only field. Will be updated after every visit to snippet.'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='slug',
            field=models.SlugField(help_text='Read only field. Will be filled automatically.'),
        ),
    ]
