# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-13 17:10
from __future__ import unicode_literals

from django.db import migrations


def add_guest_author(apps, schema_editor):
   User = apps.get_model('auth', 'User')
   Author = apps.get_model('djangobin', 'Author')
   r = User.objects.get_or_create(username = 'guest', email='guest@example.com')
   Author.objects.create(user=r[0])  # create associated author


def remove_guest_author(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    u = User.objects.filter(username='guest')
    if u:
        u[0].delete()


class Migration(migrations.Migration):

    dependencies = [
        ('djangobin', '0009_auto_20180510_0834'),
    ]

    operations = [
        migrations.RunPython(add_guest_author, remove_guest_author)
    ]
